packages:
  - "api-client"
  - "backend"
  - "comm"
  - "jupyter"
  - "nats"
  - "project"
  - "sync"
  - "sync-fs"
  - "sync-client"
  - "util"
  - "terminal"
  - "nats"
  - "compute"

onlyBuiltDependencies:
  - '@cocalc/fuse-native'
  - websocket-sftp
  - websocketfs
