ARG ARCH=

FROM sagemathinc/compute-python${ARCH}
USER root

# Because ARG doesn't work for COPY from
#   https://stackoverflow.com/questions/43473236/docker-build-arg-and-copy

COPY --from=sagemathinc/compute-sagemath-10.1-core-arm64 /usr/local/sage /usr/local/sage

# Add links for sage and sagemath
RUN  ln -sf "/usr/local/sage/sage/sage" /usr/bin/sage \
  && ln -sf "/usr/local/sage/sage/sage" /usr/bin/sagemath

RUN apt-get update && apt-get install -y libssl-dev graphviz tachyon gfortran libreadline-dev 

# Put scripts to start gap, gp, maxima, ... in /usr/local/bin
RUN sage --nodotsage -c "install_scripts('/usr/local/bin')"

WORKDIR /home/user

USER user
