channels:
  - huggingface
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - blas
  - blosc
  - bokeh
  - botorch
  - click
  - cudatoolkit
  - cycler
  - cython
  - cytoolz
  - dask
  - databricks-cli
  - dataclasses
  - distributed
  - fastparquet
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - h5py
  - huggingface_hub
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jax
  - jupyterlab
  - jupyterlab_widgets
  - kiwisolver
  - matplotlib
  - matplotlib-inline
  - mkl
  - mlflow
  - mypy_extensions
  - networkx
  - numba
  - numpy
  - pandas
  - patsy
  - pillow
  - pip
  - plotly
  - psutil
  - ptyprocess
  - pure_eval
  - py-opencv
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pygments
  - python-dateutil
  - pytorch
  - pytorch-mutex
  - re2
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - snappy
  - sqlalchemy
  - statsmodels
  - tabulate
  - tensorboard
  - tensorboardx
  - toolz
  - torchaudio
  - torchvision
  - tqdm
  - traitlets
  - wheel
  - pip:
    - tokenizers
    - transformers
