# Forked from E043 in https://github.com/kierenAW/conda_environments_for_data_science
name: cocalc-compute
channels:
  - huggingface
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - aiohttp
  - aiosignal
  - alembic
  - anyio
  - aom
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - asn1crypto
  - attrs
  - ax-platform
  - babel
  - beautifulsoup4
  - black
  - blas
  - bleach
  - blinker
  - blosc
  - bokeh
  - botorch
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - cachetools
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - configparser
  - contourpy
  - cramjam
  - cryptography
  - cudatoolkit
  - cycler
  - cython
  - cytoolz
  - dask
  - databricks-cli
  - dataclasses
  - dav1d
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - diffusers
  - distributed
  - docker-py
  - docker-pycreds
  - entrypoints
  - executing
  - expat
  - fastparquet
  - ffmpeg
  - filelock
  - flask
  - flit-core
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fribidi
  - frozenlist
  - fsspec
  - ftfy
  - gdk-pixbuf
  - gettext
  - gflags
  - gitdb
  - gitpython
  - glog
  - gmp
  - gnutls
  - google-auth
  - gpytorch
  - graphite2
  - graphviz
  - greenlet
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gtk2
  - gts
  - gunicorn
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - htmlmin
  - huggingface_hub
  - icu
  - idna
  - imagecodecs
  - imagehash
  - imageio
  - indexed_gzip
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - itsdangerous
  - jasper
  - jax
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - linear_operator
  - llvm-openmp
  - locket
  - lxml
  - lz4
  - lz4-c
  - mako
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - missingno
  - mistune
  - mkl
  - mlflow
  - msgpack-python
  - multidict
  - multimethod
  - multipledispatch
  - munkres
  - mypy_extensions
  - mysql-common
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - nodejs
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - oauthlib
  - olefile
  - opencv
  - openh264
  - openjpeg
  - openssl
  - opt_einsum
  - orc
  - pandas
  - pandas-profiling
  - pandoc
  - pandocfilters
  - pango
  - parquet-cpp
  - parso
  - partd
  - pathspec
  - patsy
  - pcre
  - pcre2
  - pexpect
  - phik
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - plotly
  - pooch
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-opencv
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycocotools
  - pycparser
  - pydantic
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyro-api
  - pyro-ppl
  - pyrsistent
  - pysocks
  - python_abi
  - python-dateutil
  - python-editor
  - python-fastjsonschema
  - pytorch
  - pytorch-mutex
  - pytz
  - pyu2f
  - pywavelets
  - pyyaml
  - pyzmq
  - querystring_parser
  - re2
  - readline
  - regex
  - requests
  - requests-oauthlib
  - rsa
  - s2n
  - sacremoses
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - six
  - smmap
  - snappy
  - sniffio
  - soupsieve
  - sqlalchemy
  - sqlite
  - sqlparse
  - stack_data
  - statsmodels
  - svt-av1
  - tabulate
  - tangled-up-in-unicode
  - tbb
  - tenacity
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorboardx
  - terminado
  - testpath
  - threadpoolctl
  - thrift
  - tifffile
  - tomli
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typeguard
  - typing_extensions
  - typing-extensions
  - tzdata
  - unicodedata2
  - urllib3
  - visions
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xz
  - yaml
  - yarl
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
    - tokenizers
    - transformers
